#!/usr/bin/env python
import sys
import os


def main(args):
    for arg in args:
        if arg.startswith("landscape"):
            break
    else:
        args.append("landscape")
    os.execvp("trial", ["trial", "-r", "glib2"] + args)
 

if __name__ == "__main__":
    main(sys.argv[1:])


# vim:ts=4:sw=4:et
