#!/usr/bin/env python

"""
Simple if ugly load testing script, obviously will need improvement if it lives
long.
"""

import os
import sys
import time

count = 10
source_dir = "/home/frank/var/"
LANDSCAPE_PLAYER_PATH = "./scripts/landscape-player"

# root check
if 'root' != os.environ['USER']:
    print "Error: This script should be run as root!"
    sys.exit(1)
# source directory check
if not os.path.exists(source_dir):
    print "Error: Source directory %s doesn't exist!" % source_dir
    sys.exit(2)
# landscape executable check
if not os.path.exists(LANDSCAPE_PLAYER_PATH):
    print "Error: Could not find landscape player %s" %(LANDSCAPE_PLAYER_PATH)
    sys.exit(3)


now = time.time()
for i in range(0, count):
    destination_dir = "/tmp/landscape_%i_%i" % (now, i)
    os.system("cp -r %s %s" % (source_dir, destination_dir))
    os.system("%s -d %s --computer-title client-%s-%s &" % (LANDSCAPE_PLAYER_PATH, destination_dir, now, i))


