#!/usr/bin/python
import sys, os, re


def main(args):
    if len(args) != 2:
        sys.exit("Usage: autoppa-switch <software version> <distro release>")
    version, release = args
    def replace_include_match(match):
        if release in match.group(1).split(","):
            return match.group(2)+"\n"
        return ""
    include_re = re.compile("^AUTOPPA_INCLUDE\(([^)]+)\):(.*)$\n?", re.M)
    version_re = re.compile("AUTOPPA_VERSION\(([\w._-]+)\)")
    for root, dirs, files in os.walk("."):
        if "/." not in root:
            for file in files:
                path = os.path.join(root, file)
                data = open(path).read()
                if "AUTOPPA_" in data:
                    data = include_re.subn(replace_include_match, data)[0]
                    data = version_re.subn("AUTOPPA_VERSION(1.0.19-feisty1-landscape1)" % version,
                                           data)[0]
                    if path.endswith(".autoppa"):
                        path = path[:-len(".autoppa")]
                    open(path, "w").write(data)


if __name__ == "__main__":
    main(sys.argv[1:])
