#!/usr/bin/python3
import sys, os
if os.path.dirname(os.path.abspath(sys.argv[0])) == os.path.abspath("scripts"):
    sys.path.insert(0, "./")
else:
    from landscape.lib.warning import hide_warnings
    hide_warnings()

from landscape.lib.fd import clean_fds

# close stray file descriptors now, before we give any other code the chance to
# create a critical FD. Even before the reactor is installed!
clean_fds()

from landscape.client.watchdog import run

if __name__ == "__main__":
    sys.exit(run())
