#!/usr/bin/env python

import dbus

from landscape.ui.model.registration.mechanism import (
    RegistrationMechanism, INTERFACE_NAME, SERVICE_NAME)
from landscape.ui.lib.polkit import listen


if __name__ == "__main__":
    dbus.mainloop.glib.DBusGMainLoop(set_as_default=True)
    bus = dbus.SystemBus()
    bus_name = dbus.service.BusName(SERVICE_NAME, bus)
    mechanism = RegistrationMechanism(bus_name)
    listen()
