#!/usr/bin/python
import sys, os

try:
    if os.path.dirname(os.path.abspath(sys.argv[0])) == os.path.abspath("scripts"):
        sys.path.insert(0, "./")
    else:
        from landscape.lib.warning import hide_warnings
        hide_warnings()

    from landscape.lib.fd import clean_fds

    # close stray file descriptors now, before we give any other code the
    # chance to create a critical FD. Even before the reactor is installed!
    clean_fds()

    # This is needed for DBUS listeners to work.
    from twisted.internet.glib2reactor import install
    install()

    from landscape.watchdog import run
except ImportError:
    # For some reasons the libraries are not importable for now. We are
    # probably during an upgrade procedure, so let's exit, expecting the
    # dependencies to be fixed at next run.
    sys.exit(2)

if __name__ == "__main__":
    sys.exit(run())
