#!/usr/bin/python3
import sys, os
if os.path.dirname(os.path.abspath(sys.argv[0])) == os.path.abspath("scripts"):
    sys.path.insert(0, "./")

from landscape.client.package.reporter import main


if __name__ == "__main__":
    main(sys.argv[1:])
