#!/usr/bin/env python

import dbus

from landscape.configuration import LandscapeSetupConfiguration
from landscape.ui.model.configuration.mechanism import (
    ConfigurationMechanism, INTERFACE_NAME, SERVICE_NAME, listen)


if __name__ == "__main__":
    dbus.mainloop.glib.DBusGMainLoop(set_as_default=True)
    bus = dbus.SystemBus()
    bus_name = dbus.service.BusName(SERVICE_NAME, bus)
    config = LandscapeSetupConfiguration()
    mechanism = ConfigurationMechanism(config, bus_name)
    listen()
