#!/usr/bin/python
import sys, os
if os.path.isdir("landscape"):
    sys.path.insert(0, "./")

from twisted.internet import reactor

from landscape.sysinfo.deployment import run


if __name__ == "__main__":
    run(sys.argv[1:], reactor)
