#!/usr/bin/python
import sys, os
if os.path.dirname(os.path.abspath(sys.argv[0])) == os.path.abspath("scripts"):
    sys.path.insert(0, "./")

from landscape.broker.registration import is_cloud_managed

# We return 0 if it succeeds
sys.exit(not is_cloud_managed())
