#!/usr/bin/python

import os
import dbus
import subprocess

from gi.repository import GObject, Gtk

from aptdaemon.client import AptClient
from defer import inline_callbacks
from aptdaemon import policykit1
from aptdaemon.gtk3widgets import AptProgressDialog


script = "/usr/bin/landscape-client-settings-ui"


def on_transaction_done(transaction, exit):
    Gtk.main_quit()
    # Install may have failed
    if os.path.exists(script):
        subprocess.call(script)


@inline_callbacks
def install_package():
    aptclient = AptClient()
    bus = dbus.SystemBus()
    name = bus.get_unique_name()
    action = policykit1.PK_ACTION_INSTALL_OR_REMOVE_PACKAGES
    flags = policykit1.CHECK_AUTH_ALLOW_USER_INTERACTION
    yield policykit1.check_authorization_by_name(name, action, flags=flags)
    transaction = yield aptclient.install_packages(
        ["landscape-client-ui"])
    transaction.connect('finished', on_transaction_done)
    dia = AptProgressDialog(transaction)
    dia.run(close_on_finished=True, show_error=True)


def main():
    dialog = Gtk.MessageDialog(
        flags=Gtk.DialogFlags.MODAL, type=Gtk.MessageType.INFO,
        buttons=Gtk.ButtonsType.CANCEL)
    dialog.set_markup(
        "<big><b>%s</b></big>\n\n%s" % (
            "Landscape client is not installed",
            "You need to install Landscape client to be able to configure it. "
            "Do you want to intall it now?"))
    dialog.set_title("Install Landscape client?")
    dialog.add_button("Install", Gtk.ResponseType.YES)
    result = dialog.run()
    dialog.destroy()
    if result == Gtk.ResponseType.YES:
        install_package()
    else:
        Gtk.main_quit()
    return False


if __name__ == "__main__":
    if not os.path.exists(script):
        GObject.idle_add(main)
        Gtk.main()
    else:
        subprocess.call(script)
