name: 'Run the secscan tool'
description: 'Run the secscan tool against landscape-client deb/snap/charm'

inputs:
  results-dir:
    description: 'Prefix for the path to write the scan results to.'
    required: true

  scanner:
    description: 'Name of the scanner to pass to secscan'
    required: true
  use-batch: 
    description: 'Whether to use batch mode for the scan.'
    required: true
  
  deb-path:
    description: 'Path to the .deb file to scan.'
    required: true
  deb-base:
    description: 'Base Ubuntu release to scan against'
    required: true
  deb-arch:
    description: 'Base architecture to scan against'
    required: true
  deb-pockets:
    description: 'Space-separated list of base pockets to scan against.'
    required: false

  snap-channel:
    description: 'Channel of the snap to scan'
    required: true

  charm-risk:
    description: 'Risk level of the charm artifact'
    required: true
  charm-arch:
    description: 'Architecture of the charm artifact'
    required: true
  charm-base:
    description: 'Base of the charm artifact'
    required: true

  ssdlc-version:
    description: 'Version of the artifact being scanned'
    required: true
    default: ''
  ssdlc-risk:
    description: 'Risk level of the scanned artifact'
    required: true
    default: ''
  ssdlc-cycle:
    description: 'Cycle the scan is submitted for'
    required: true
    default: ''

runs:
  using: "composite"
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        sudo snap install canonical-secscan-client
        sudo snap connect canonical-secscan-client:home :home
    - name: Run secscan tool
      id: run-secscan
      shell: bash
      run: |
        ## This is designed to try to run all three types of scans.
        ## If there is a failure in one, it should not prevent the others from running.
        set +e

        mkdir -p "${RESULTS_DIR}"

        secscan_command=(secscan-client)
        if [ "$USE_BATCH" = "true" ]; then
          secscan_command+=(--batch)
        fi

        ssdlc_args=()
        if [ -n "${SSDLC_VERSION}" ] && [ -n "${SSDLC_RISK}" ] && [ -n "${SSDLC_CYCLE}" ]; then
          ssdlc_args+=(--ssdlc-product-name landscape-client)
          ssdlc_args+=(--ssdlc-product-version "${SSDLC_VERSION}")
          ssdlc_args+=(--ssdlc-risk "${SSDLC_RISK}")
          ssdlc_args+=(--ssdlc-cycle "${SSDLC_CYCLE}")
        fi

        SNAP_REVISION=$(snap info landscape-client | grep "${SNAP_CHANNEL}" | grep -Eo "\([0-9]+\)" | tr -d "()")
        if [ -z "${SNAP_REVISION}" ]; then
          echo "::error::Failed to determine snap revision for channel '${SNAP_CHANNEL}'" >&2
        else
          "${secscan_command[@]}" submit --token snap.token --scanner "${SCANNER}" --type package --format snap \
            "${ssdlc_args[@]}" --wait-and-print landscape-client="${SNAP_REVISION}" | tee "${RESULTS_DIR}/snap.txt"
          "${secscan_command[@]}" log --token snap.token | tee "${RESULTS_DIR}/snap.log"
        fi

        if [ -z "${DEB_PATH}" ]; then
          echo "::error::Deb path is not set" >&2
        else
          pocket_args=()
          for pocket in ${DEB_POCKETS}; do
            pocket_args+=(--base-pocket "$pocket")
          done
          "${secscan_command[@]}" submit --token deb.token --scanner "${SCANNER}" --type package --format deb --base "${DEB_BASE}" \
            --base-arch "${DEB_ARCH}" "${pocket_args[@]}" "${ssdlc_args[@]}" --wait-and-print "${DEB_PATH}" | tee "${RESULTS_DIR}/deb.txt"
          "${secscan_command[@]}" log --token deb.token | tee "${RESULTS_DIR}/deb.log"
        fi

        "${secscan_command[@]}" submit --token charm.token --scanner "${SCANNER}" --type package --format charm \
          "${ssdlc_args[@]}" --wait-and-print landscape-client/"${CHARM_RISK}"@"${CHARM_ARCH}"/"${CHARM_BASE}" | tee "${RESULTS_DIR}/charm.txt"
        "${secscan_command[@]}" log --token charm.token | tee "${RESULTS_DIR}/charm.log"
      env:
        RESULTS_DIR: ${{ inputs.results-dir }}
        SCANNER: ${{ inputs.scanner }}
        USE_BATCH: ${{ inputs.use-batch }}
        DEB_PATH: ${{ inputs.deb-path }}
        DEB_BASE: ${{ inputs.deb-base }}
        DEB_ARCH: ${{ inputs.deb-arch }}
        DEB_POCKETS: ${{ inputs.deb-pockets }}
        SNAP_CHANNEL: ${{ inputs.snap-channel }}
        CHARM_RISK: ${{ inputs.charm-risk }}
        CHARM_ARCH: ${{ inputs.charm-arch }}
        CHARM_BASE: ${{ inputs.charm-base }}
        SSDLC_VERSION: ${{ inputs.ssdlc-version }}
        SSDLC_RISK: ${{ inputs.ssdlc-risk }}
        SSDLC_CYCLE: ${{ inputs.ssdlc-cycle }}
