name: landscape-client
base: core22
version: '0.1'
summary: Client for the Canonical systems managemenet product Landscape
description: |
  This client, when installed, allows a machine to connect to the
  Landscape server and be remotely managed by it.

grade: devel # must be 'stable' to release into candidate/stable channels
architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: ppc64le
  - build-on: riscv
  - build-on: s390x
confinement: devmode # use 'strict' once you have the right plugs and slots

layout:
  /var/lib/landscape:
    bind: $SNAP_DATA/var/lib/landscape

environment:
  PYTHONPATH: $SNAP/usr/lib/python3/dist-packages:$SNAP/usr/lib/python3.10/dist-packages

apps:
  debug-shell:
    command: bin/debug-shell.wrapper
    plugs:
      - network
  landscape-config:
    command: bin/landscape-config
    plugs:
      - network

parts:
  landscape-client:
    plugin: python
    source: https://github.com/bceverly/landscape-client.git
    python-packages:
      - convoy-python
      - distutils-extra-python
      - twisted
    build-packages:
      - build-essential
      - python3-flake8 
      - python3-coverage
      - python3-twisted 
      - python3-distutils-extra
      - python3-mock 
      - python3-configobj 
      - python3-netifaces 
      - python3-pycurl 
      - python3-pip
      - python3-distutils
      - python3-twisted 
      - python3-mock 
      - python3-configobj 
      - python3-netifaces 
      - python3-pycurl
      - software-properties-common
    override-build: |
      #snapcraftctl build
      python3 -m venv build/venv --system-site-packages
      ln -sf build/venv/bin bin
      bin/pip install -U convoy-python distutils-extra-python twisted pre-commit
      make build3
    stage-packages:
      - landscape-client
      - landscape-common
      - language-pack-en
      - python3-oops
      - python3-pip
      - python3-twisted
    override-stage: |
      #snapcraftctl stage
      craftctl default
      # Copy the landscape-config script over
      mkdir -p "${SNAPCRAFT_PRIME}/bin"
      cp  "${SNAPCRAFT_PART_SRC}/scripts/landscape-config" "${SNAPCRAFT_PRIME}/bin/"
    override-prime: |
      rm -rf $CRAFT_PRIME/bin/debug-shell.wrapper
      craftctl default
  local:
    plugin: dump
    source: tree
