name: Build Jammy

on:

  # Enable manual run against a specific ref
  workflow_dispatch:
    inputs:
      ref:
        description: "Git ref to build from (branch name, tag, commit SHA, etc.)"
        required: false
        default: ''

  # Enable use from other workflows
  workflow_call:
    inputs:
      ref:
        description: "Git ref to build from (branch name, tag, commit SHA, etc.)"
        required: true
        type: string
    outputs:
      debbuildid:
        description: "ID of the deb build artifact"
        value: ${{ jobs.build-jammy.outputs.debbuildid }}
      sourcebuildid:
        description: "ID of the source build artifact"
        value: ${{ jobs.build-jammy.outputs.sourcebuildid }}

  # Run on any non-beta tag pushes (beta tags are for the PPA deploy workflow)
  push:
    tags-ignore:
      - "[0-9][0-9].[0-9][0-9]-beta**"

jobs:
  build-jammy:
    name: Build Jammy
    runs-on: ubuntu-22.04
    outputs:
      debbuildid: ${{ steps.upload-deb-build.outputs.artifact-id }}
      sourcebuildid: ${{ steps.upload-source-build.outputs.artifact-id }}

    steps:
      # Get the reference to build from, if provided.
      - name: Get reference to build from
        id: get-reference
        run: echo "ref=${{ github.event.inputs.ref || github.event.repository.default_branch }}" >> $GITHUB_OUTPUT

      - name: Check out Git repository
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.get-reference.outputs.ref }}
          submodules: true

      - name: Install build dependencies
        run: sudo apt update && sudo apt install -y debhelper po-debconf libdistro-info-perl dh-python python3-dev python3-distutils-extra lsb-release gawk net-tools python3-apt python3-twisted python3-configobj python3-pycurl python3-pytest locales-all devscripts

      - name: Build .deb
        run: |
          mkdir -p ../source-build
          mkdir -p ../deb-build

          make tarball
          rm -r sdist/

          debuild --no-lintian -S -sa --no-sign
          cp ../landscape-client_* ../source-build/

          # If we use this to automatically make releases or upload to the PPA, we should enable checks.
          DEB_BUILD_OPTIONS=nocheck debuild -b --no-sign
          cp ../landscape-client_*.orig.tar.gz ../deb-build/
          cp ../landscape-*.*deb ../deb-build/

          # Artifact upload steps do not allow relative paths
          mv ../source-build/ ./
          mv ../deb-build/ ./

      - name: Upload source build
        uses: actions/upload-artifact@v6
        id: upload-source-build
        with:
          name: source-build
          path: ./source-build/

      - name: Upload deb build
        uses: actions/upload-artifact@v6
        id: upload-deb-build
        with:
          name: deb-build
          path: ./deb-build/

      - run: |
          echo "::notice::Built from ref: ${{ steps.get-reference.outputs.ref }}"
          echo "::notice::Deb build artifact ID: ${{ steps.upload-deb-build.outputs.artifact-id }}"
          echo "::notice::Source build artifact ID: ${{ steps.upload-source-build.outputs.artifact-id }}"
