name: ci
on: [pull_request, workflow_dispatch]
jobs:
  check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-22.04", "ubuntu-24.04"]
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          submodules: true
      - run: make depends-ci
      - run: make check TRIAL=/usr/bin/trial3
      
  run-ruff:
    if: '!github.event.pull_request.draft'
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          submodules: true
  
      - uses: astral-sh/ruff-action@4919ec5cf1f49eff0871dbcea0da843445b837e6 # v3.6.1
      - run: make ruff-check
