name: Codecov upload

on: [push, pull_request]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: make depends-ci
      - run: make coverage TRIAL=/usr/bin/trial3
      - name: upload
        uses: codecov/codecov-action@v3
