name: Codecov upload

on: [push, pull_request]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          submodules: true
      - run: make depends-ci
      - run: make coverage TRIAL=/usr/bin/trial3
      - name: upload
        uses: codecov/codecov-action@0fb7174895f61a3b6b78fc075e0cd60383518dac # v5.5.5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
