name: TiCS static analysis

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'  # Run at 6:00a (arbitrary) to avoid peak activity on runners
jobs:
  TICS:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Make coverage report for TiCS
        run: make prepare-tics-analysis
      - name: TICS GitHub Action
        uses: tiobe/tics-github-action@v3
        with:
          project: landscape-client
          viewerUrl: https://canonical.tiobe.com/tiobeweb/TICS/api/cfg?name=default
          ticsAuthToken: ${{ secrets.TICSAUTHTOKEN }}
          installTics: true
          filelist: .  # whole project for nightly/on-demand runs
