name: TiCS static analysis

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  TICS:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Make coverage report for TiCS
        run: make tics-analysis
      - name: TICS GitHub Action
        uses: tiobe/tics-github-action@v2
        with:
          projectName: landscape-client
          ticsConfiguration: https://canonical.tiobe.com/tiobeweb/TICS/api/cfg?name=default
          ticsAuthToken: ${{ secrets.TICSAUTHTOKEN }}
          installTics: true
          filelist: .  # whole project for nightly/on-demand runs
