name: TiCS static analysis

# Temp: run once weekly to reduce infra load
on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 0'  # Run at 6:00a (arbitrary) to avoid peak activity on runners
jobs:
  TICS:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Make coverage report for TiCS
        run: make prepare-tics-analysis
      - name: TICS GitHub Action
        uses: tiobe/tics-github-action@v3
        with:
          mode: qserver
          project: landscape-client
          branchdir: ${{ github.workspace }}
          viewerUrl: https://canonical.tiobe.com/tiobeweb/TICS/api/cfg?name=default
          ticsAuthToken: ${{ secrets.TICSAUTHTOKEN }}
          installTics: true
          filelist: .  # whole project for nightly/on-demand runs
